const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'src', 'data');
const animals = JSON.parse(fs.readFileSync(path.join(dataDir, 'animals.json'), 'utf8'));
const translations = JSON.parse(fs.readFileSync(path.join(dataDir, 'animal-translations.json'), 'utf8'));

function hasNameAndDesc(entry) {
  return entry && entry.name && entry.description;
}

function getMissing(locale) {
  const localeData = translations[locale] || {};
  return animals.filter(a => !hasNameAndDesc(localeData[a.id]));
}

// Comprehensive Arabic translations
const arTranslations = {
  // Mammals
  'african-elephant': { name: 'الفيل الأفريقي', description: 'الفيل الأفريقي هو أكبر حيوان بري على وجه الأرض، يتميز بحجمه الهائل وخراطيمه وأنيابه الظاهرة.' },
  'asian-elephant': { name: 'الفيل الآسيوي', description: 'الفيل الآسيوي أصغر من نظيره الأفريقي، بأذنين أصغر ورأس أكثر تدويراً.' },
  'white-rhinoceros': { name: 'وعل أبيض', description: 'الوعل الأبيض هو أكبر خمسة أنواع من وحيد القرن، يتميز بفمه الواسع وطبيعته الهادئة.' },
  'black-rhinoceros': { name: 'وعل أسود', description: 'الوعل الأسود من فصيلة العواشب بشفة علوية مقوسة، مشهور بطبعه الهجومي.' },
  'hippopotamus': { name: 'فرس النهر', description: 'فرس النهر ثديي نصف مائي ضخم يقضي معظم نهاره في الماء للحفاظ على برودته.' },
  'giraffe': { name: 'زرافة', description: 'الزرافة هي أطول حيوان بري على قيد الحياة، تستخدم رقبتها الطويلة للوصول إلى الأغصان العالية.' },
  'okapi': { name: 'أوكيبي', description: 'الأوكيبي حيوان غابات خجول قريب من الزرافة، بأرجل مخططة فريدة.' },
  'cape-buffalo': { name: 'جاموس أفضف', description: 'الجاموس الأفضف من فصيلة البقر الكبيرة مشهور بطبيعته غير المتوقعة وقوارنيه المنحنية الضخمة.' },
  'american-bison': { name: 'بيسون أمريكي', description: 'البيسون الأمريكي هو أكبر حيوان بري في أمريكا الشمالية، كان يتجول في أسراب ضخمة في السهول الكبرى.' },
  'water-buffalo': { name: 'جاموس مائي', description: 'الجاموس المائي من فصيلة البقر الكبيرة يُستخدم على نطاق واسع في الزراعة في آسيا.' },
  'yak': { name: 'ياك', description: 'الياك من فصيلة البقر ذي الشعر الطويل، متأقلم مع المرتفعات العالية في الهيمالايا.' },
  'domestic-cattle': { name: 'بقر منزلي', description: 'البقر المنزلي من فصيلة الحوافر الكبيرة يُربى للحوم والحليب والجلد.' },
  'gaur': { name: 'جور', description: 'الجور هو أكبر أنواع الثيران البرية في العالم، أصلي من جنوب وجنوب شرق آسيا.' },
  'saiga-antelope': { name: 'غزال سايغا', description: 'غزال سايغا مشهور بأنفه غير المعتاد والمنتفخ الذي يرشح الغبار ويوصل الهواء.' },
  'addax': { name: 'أض Hooks', description: 'أضHooks منبسط متأقلم مع الحياة في صحراء الصحراء الكبرى، بقرون حلزونية طويلة وفراء أبيض.' },
  'oryx': { name: 'حيوان وحيد القرن', description: 'حيوان وحيد القرن من فصيلة الظباء الكبيرة بقرون طويلة مستقيمة، متأقلم مع البيئات الجافة.' },
  'tiger': { name: 'نمر', description: 'النمر هو أكبر القطط الكبيرة الحية، بفرو برتقالي مخطط بالأسود وقدرة صيد قوية.' },
  'lion': { name: 'أسد', description: 'الأسد هو القط الاجتماعي الوحيد الذي يعيش في مجموعات تسمى_groups.' },
  'leopard': { name: 'نمر', description: 'النمر حيوان بري متوسط الحجم من فصيلة السنوريات.' },
  'snow-leopard': { name: 'نمر ثلجي', description: 'النمر الثلجي حيوان بري يعيش في المناطق الجبلية في آسيا الوسطى.' },
  'jaguar': { name: 'نمر أمريكا', description: 'النمر الأمريكي هو أكبر القطط في الأمريكتين.' },
  'cheetah': { name: 'فهد', description: 'الفهد هو أسرع حيوان بري على وجه الأرض.' },
  'cougar': { name: 'أسد الجبال', description: 'أسد الجبال هو أكبر القطط البرية في غرب نصف الكرة الغربي.' },
  'clouded-leopard': { name: 'نمر مُلبّد', description: 'النمر المُلبّد حيوان بري من فصيلة السنوريات.' },
  'serval': { name: 'سنور', description: 'السنور حيوان بري من فصيلة السنوريات يعيش في أفريقيا.' },
  'caracal': { name: 'قةطل', description: 'القةطل حيوان بري من فصيلة السنوريات.' },
  'pallas-s-cat': { name: 'قط بيل', description: 'قط بيل حيوان بري صغير من فصيلة السنوريات.' },
  'sand-cat': { name: 'قط الرمال', description: 'قط الرمال حيوان بري يعيش في الصحراء.' },
  'fishing-cat': { name: 'قط صياد', description: 'القط الصياد حيوان بري يصطاد الأسماك.' },
  'brown-bear': { name: 'دب بني', description: 'الدب البني حيوان بري كبير من فصيلة الدببة.' },
  'grizzly-bear': { name: 'دب رمادي', description: 'الدب الرمادي حيوان بري من فصيلة الدببة.' },
  'polar-bear': { name: 'دب قطبي', description: 'الدب القطبي حيوان بري يعيش في القطب الشمالي.' },
  'american-black-bear': { name: 'دب أسود أمريكي', description: 'الدب الأسود الأمريكي حيوان بري في أمريكا الشمالية.' },
  'asian-black-bear': { name: 'دب أسود آسيوي', description: 'الدب الأسود الآسيوي حيوان بري في آسيا.' },
  'spectacled-bear': { name: 'دب بنظارات', description: 'الدب بنظارات حيوان بري في أمريكا الجنوبية.' },
  'sun-bear': { name: 'دب الشمس', description: 'دب الشمس حيوان بري صغير في جنوب شرق آسيا.' },
  'sloth-bear': { name: 'دب كسول', description: 'الدب الكسول حيوان بري في الهند وسريلانكا.' },
  'giant-panda': { name: 'باندا عملاقة', description: 'الباندا العملاقة حيوان بري في الصين.' },
  'andean-bear': { name: 'دب الأند', description: 'دب الأند حيوان بري في أمريكا الجنوبية.' },
  'gray-wolf': { name: 'ذئب رمادي', description: 'الذئب الرمادي حيوان بري من فصيلة الكلبيات.' },
  'arctic-wolf': { name: 'ذئب قطبي', description: 'الذئب القطبي حيوان بري في القطب الشمالي.' },
  'red-fox': { name: 'ثعلب أحمر', description: 'الثعلب الأحمر حيوان بري من فصيلة الكلبيات.' },
  'fennec-fox': { name: 'ثعلب فنّك', description: 'الثعلب الفنّك حيوان بري صغير في الصحراء.' },
  'arctic-fox': { name: 'ثعلب قطبي', description: 'الثعلب القطبي حيوان بري في القطب الشمالي.' },
  'african-wild-dog': { name: 'كلب بري أفريقي', description: 'الكلب البري الأفريقي حيوان بري في أفريقيا.' },
  'coyote': { name: 'كويوت', description: 'الكويوت حيوان بري في أمريكا الشمالية.' },
  'jackal': { name: 'ضبع', description: 'الضبع حيوان بري في أفريقيا وآسيا.' },
  'dingo': { name: 'دنغو', description: 'الدنغو حيوان بري في أستراليا.' },
  'maned-wolf': { name: 'ذئب ذيل', description: 'الذئب ذو الذيل الطويل حيوان بري في أمريكا الجنوبية.' },
  'western-gorilla': { name: 'غوريلا غربية', description: 'الغوريلا الغربية حيوان بري في أفريقيا.' },
  'eastern-gorilla': { name: 'غوريلا شرقية', description: 'الغوريلا الشرقية حيوان بري في أفريقيا.' },
  'chimpanzee': { name: 'شمبانزي', description: 'الشمبانزي حيوان بري في أفريقيا.' },
  'bonobo': { name: 'بونوبو', description: 'البونوبو حيوان بري في أفريقيا.' },
  'orangutan': { name: 'أورانغوتان', description: 'الأورانغوتان حيوان بري في آسيا.' },
  'siamang': { name: 'سيامانغ', description: 'السيامانغ حيوان بري في آسيا.' },
  'gibbon': { name: 'جيبون', description: 'الجيبون حيوان بري في آسيا.' },
  'mandrill': { name: 'ماند릴', description: 'الماند릴 حيوان بري في أفريقيا.' },
  'proboscis-monkey': { name: 'قرد أنفي', description: 'القرد الأنفي حيوان بري في آسيا.' },
  'spider-monkey': { name: 'قرد عنكبوت', description: 'القرد العنكبوت حيوان بري في أمريكا الجنوبية.' },
  'capuchin-monkey': { name: 'قرد كابوتشين', description: 'القرد الكابوتشين حيوان بري في أمريكا الجنوبية.' },
  'lemur': { name: 'ليمور', description: 'الليمور حيوان بري في مدغشقر.' },
  'indri': { name: 'إنديري', description: 'الإنديري حيوان بري في مدغشقر.' },
  'tarsier': { name: 'ترسير', description: 'الترسير حيوان بري في آسيا.' },
  'aye-aye': { name: 'أي أ', description: 'الأي أ حيوان بري في مدغشقر.' },
  'blue-whale': { name: 'حوت أزرق', description: 'الحوت الأزرق هو أكبر حيوان على وجه الأرض.' },
  'humpback-whale': { name: 'حوت سن宝宝', description: 'الحوت السن宝宝 حيوان بري بحري.' },
  'sperm-whale': { name: 'حوتulman', description: 'الحوتulman حيوان بري بحري.' },
  'killer-whale': { name: 'حوت قاتل', description: 'الحوت القاتل حيوان بري بحري.' },
  'bottlenose-dolphin': { name: 'دلفين أنف زجاجي', description: 'الدلفين أنف الزجاجي حيوان بري بحري.' },
  'narwhal': { name: 'ناروال', description: 'الناروال حيوان بري بحري.' },
  'beluga-whale': { name: 'حوت أبيض', description: 'الحوت الأبيض حيوان بري بحري.' },
  'manatee': { name: 'otten', description: 'الotten حيوان بري بحري.' },
  'dugong': { name: 'دوغون', description: 'الدوغون حيوان بري بحري.' },
  'walrus': { name: 'فول', description: 'الفول حيوان بري بحري.' },
  'elephant-seal': { name: 'فقمة فيل', description: 'فقمة الفيل حيوان بري بحري.' },
  'leopard-seal': { name: 'فقمة نمر', description: 'فقمة النمر حيوان بري بحري.' },
  'harp-seal': { name: 'فقمة القيثارة', description: 'فقمة القيثارة حيوان بري بحري.' },
  'sea-otter': { name: 'قط بحري', description: 'القط البحري حيوان بري بحري.' },
  'hawaiian-monk-seal': { name: 'فقمة هاواي', description: 'فقمة هاواي حيوان بري بحري.' },
  'steller-sea-lion': { name: 'أسد بحري', description: 'الأسد البحري حيوان بري بحري.' },
  'capybara': { name: 'كابي', description: 'الكابي حيوان بري في أمريكا الجنوبية.' },
  'beaver': { name: 'قنادس', description: 'القنادس حيوان بري في أمريكا الشمالية.' },
  'porcupine': { name: 'خنزير شوك', description: 'خنزير الشوك حيوان بري بشوك.' },
  'crested-porcupine': { name: 'خنزير شوك متوّج', description: 'خنزير الشوك المتوّج حيوان بري بشوك.' },
  'naked-mole-rat': { name: 'جرد عاري', description: 'الجرد العاري حيوان بري تحت الأرض.' },
  'prairie-dog': { name: 'كلب السهوب', description: 'كلب السهوب حيوان بري في أمريكا الشمالية.' },
  'squirrel': { name: 'سنجاب', description: 'السنجاب حيوان بري صغير.' },
  'chinchilla': { name: 'تشينتشيلا', description: 'التشينتشيلا حيوان بري في أمريكا الجنوبية.' },
  'guinea-pig': { name: 'خنزير غينيا', description: 'خنزير الغينيا حيوان بري في أمريكا الجنوبية.' },
  'hamster': { name: 'هملتر', description: 'الهملتر حيوان بري صغير.' },
  'mouse': { name: 'فأر', description: 'الفأر حيوان بري صغير.' },
  'rat': { name: 'جرذ', description: 'الجرذ حيوان بري صغير.' },
  'indian-flying-fox': { name: 'ثعلب طائر هندي', description: 'الثعلب الطائر الهندي حيوان بري في الهند.' },
  'little-brown-bat': { name: 'خفاش بني صغير', description: 'الخفاش البني الصغير حيوان بري ليلي.' },
  'mexican-free-tailed-bat': { name: 'خفاش مكسيكي', description: 'الخفاش المكسيكي حيوان بري في أمريكا الشمالية.' },
  'fruit-bat': { name: 'خفاش فاكهة', description: 'خفاش الفاكهة حيوان بري ليلي.' },
  'horseshoe-bat': { name: 'خفاش حدوة الحصان', description: 'خفاش حدوة الحصان حيوان بري ليلي.' },
  'vampire-bat': { name: 'خفاش مصاص', description: 'خفاش المصاص حيوان بري ليلي.' },
  'megabat': { name: 'خفاش كبير', description: 'الخفاش الكبير حيوان بري ليلي.' },
  'red-kangaroo': { name: 'كنغر أحمر', description: 'الكنغر الأحمر حيوان بري في أستراليا.' },
  'grey-kangaroo': { name: 'كنغر رمادي', description: 'الكنغر الرمادي حيوان بري في أستراليا.' },
  'wallaby': { name: 'والبي', description: 'الوالبي حيوان بري في أستراليا.' },
  'tree-kangaroo': { name: 'كنغر شجري', description: 'الكنغر الشجري حيوان بري في أستراليا.' },
  'quokka': { name: 'كوكة', description: 'الكوكة حيوان بري في أستراليا.' },
  'wombat': { name: 'وombat', description: 'الوombat حيوان بري في أستراليا.' },
  'koala': { name: 'كوالا', description: 'الكوالا حيوان بري في أستراليا.' },
  'tasmanian-devil': { name: 'شيطان تسمانيا', description: 'شيطان تسمانيا حيوان بري في أستراليا.' },
  'quoll': { name: 'كوول', description: 'الكوول حيوان بري في أستراليا.' },
  'numbat': { name: 'نومبات', description: 'النومبات حيوان بري في أستراليا.' },
  'bandicoot': { name: 'باندي', description: 'الباندي حيوان بري في أستراليا.' },
  'sugar-glider': { name: 'زاحف سكر', description: 'زاحف السكر حيوان بري في أستراليا.' },
  'possum': { name: 'بوسم', description: 'البوسم حيوان بري في أستراليا.' },
  'badger': { name: 'غرير', description: 'الغرير حيوان بري في أمريكا الشمالية.' },
  'fisher': { name: 'سمّاك', description: 'السمّاك حيوان بري في أمريكا الشمالية.' },
  'pine-marten': { name: 'martinصنوبر', description: 'martinالصنوبر حيوان بري في أوروبا.' },
  'stoat': { name: 'ثعلب', description: 'الثعلب حيوان بري صغير.' },
  'weasel': { name: '(floor)', description: '(floor) حيوان بري صغير.' },
  'european-polecat': { name: 'polecat europ', description: 'polecat europ حيوان بري في أوروبا.' },
  'mink': { name: 'مينكس', description: 'المينكس حيوان بري صغير.' },
  'coati': { name: 'كواتي', description: 'الكواتي حيوان بري في أمريكا الجنوبية.' },
  'kinkajou': { name: 'كين', description: 'الكين حيوان بري في أمريكا الجنوبية.' },
  'hedgehog': { name: 'قنفذ', description: 'القنفذ حيوان بري بشوك.' },
  'tenrec': { name: 'تنّרק', description: 'التنّרק حيوان بري في مدغشقر.' },
  'shrew': { name: ' عدة', description: 'العدة حيوان بري صغير.' },
  'star-nosed-mole': { name: 'قنفذ نجمي', description: 'القنفذ النجمي حيوان بري تحت الأرض.' },
  'golden-mole': { name: 'قنفذ ذهبي', description: 'القنفذ الذهبي حيوان بري تحت الأرض.' },
  'solenodon': { name: 'سولينودون', description: 'السولينودون حيوان بري في الكاريبي.' },
  'elephant-shrew': { name: 'قنفذ فيلي', description: 'القنفذ الفيلي حيوان بري في أفريقيا.' },
  'chinese-pangolin': { name: 'بغل صيني', description: 'البغل الصيني حيوان بري في الصين.' },
  'sunda-pangolin': { name: 'بغل سوندا', description: 'البغل السوندا حيوان بري في آسيا.' },
  'indian-pangolin': { name: 'بغل هندي', description: 'البغل الهندي حيوان بري في الهند.' },
  'white-bellied-pangolin': { name: 'بغل أبيض البطن', description: 'البغل أبيض البطن حيوان بري في أفريقيا.' },
  'giant-pangolin': { name: 'بغل عملاق', description: 'البغل العملاق حيوان بري في أفريقيا.' },
  'giant-armadillo': { name: 'مدنية عملاقة', description: 'المدنية العملاقة حيوان بري في أمريكا الجنوبية.' },
  'nine-banded-armadillo': { name: 'مدنية تسعة أشرطة', description: 'المدنية تسعة أشرطة حيوان بري في أمريكا الشمالية.' },
  'pink-fairy-armadillo': { name: 'مدنية حورية وردية', description: 'المدنية الحورية الوردية حيوان بري في أمريكا الجنوبية.' },
  'southern-three-banded-armadillo': { name: 'مدنية ثلاثة أشرطة', description: 'المدنية ثلاثة أشرطة حيوان بري في أمريكا الجنوبية.' },
  'giant-anteater': { name: 'آكل النمل العملاق', description: 'آكل النمل العملاق حيوان بري في أمريكا الجنوبية.' },
  'two-toed-sloth': { name: 'كسول ثنائري الأصابع', description: 'الكسول ثنائري الأصابع حيوان بري في أمريكا الجنوبية.' },
  'southern-tamandua': { name: 'تاندואה', description: 'التاندואה حيوان بري في أمريكا الجنوبية.' },
  'aardvark': { name: 'آكل النمل', description: 'آكل النمل حيوان بري في أفريقيا.' },
  'bat-eared-fox': { name: 'ثعلب بأذني خفاش', description: 'الثعلب بأذني خفاش حيوان بري في أفريقيا.' },
  'fossa': { name: 'فوسا', description: 'الفوسا حيوان بري في مدغشقر.' },
  'aardwolf': { name: 'كلب الأرض', description: 'كلب الأرض حيوان بري في أفريقيا.' },
  'spotted-hyena': { name: 'ضبع مرقط', description: 'الضبع المرقط حيوان بري في أفريقيا.' },
  'striped-hyena': { name: 'ضبع مخطط', description: 'الضبع المخطط حيوان بري في أفريقيا وآسيا.' },
  'martens': { name: 'مارتن', description: 'المارتن حيوان بري صغير.' },
  'sable': { name: 'سابل', description: 'السابل حيوان بري في روسيا.' },
  'hog-badger': { name: 'غرير خنزير', description: 'الغرير الخنزير حيوان بري في آسيا.' },
  'raccoon-dog': { name: 'كلب رaccoon', description: 'كلب ال raccoon حيوان بري في آسيا.' },
  'crabeater-seal': { name: 'فقمة آكلة السرطان', description: 'فقمة آكلة السرطان حيوان بري بحري.' },
  'weddell-seal': { name: 'فقمة ويديل', description: 'فقمة ويديل حيوان بري بحري.' },
  'ross-seal': { name: 'فقمة روس', description: 'فقمة روس حيوان بري بحري.' },
  'arctic-ground-squirrel': { name: 'سنجاب أرضي قطبي', description: 'السنجاب الأرضي القطبي حيوان بري في القطب الشمالي.' },
  'nutria': { name: 'نوتريا', description: 'النوتريا حيوان بري في أمريكا الجنوبية.' },
  'african-crested-porcupine': { name: 'خنزير شوك أفريقي متوّج', description: 'خنزير الشوك الأفريقي المتوّج حيوان بري في أفريقيا.' },
  'springhare': { name: 'أرنب ربيعي', description: 'الأرنب الربيعي حيوان بري في أفريقيا.' },
  'cane-rat': { name: 'جرذ قصب', description: 'الجرذ القصب حيوان بري في أفريقيا.' },
  'paca': { name: 'باكا', description: 'الباكا حيوان بري في أمريكا الجنوبية.' },
  'agouti': { name: 'أغوتي', description: 'الأغوتي حيوان بري في أمريكا الجنوبية.' },
  'mara': { name: 'مارا', description: 'المارا حيوان بري في أمريكا الجنوبية.' },
  'rock-hyrax': { name: 'عرس صخري', description: 'العرس الصخري حيوان بري في أفريقيا وآسيا.' },
  'cape-hyrax': { name: 'عرس أفضف', description: 'العرس الأفضف حيوان بري في أفريقيا.' },
  'hyrax': { name: 'عرس', description: 'العرس حيوان بري في أفريقيا وآسيا.' },
  'golden-moles': { name: 'قنافذ ذهبية', description: 'القنافذ الذهبية حيوان بري تحت الأرض.' },
  'elephant-shrews': { name: 'قنافذ فيلية', description: 'القنافذ الفيلية حيوان بري في أفريقيا.' },
  'fennec-foxes': { name: 'ثعالب فنّكة', description: 'الثعالب الفنّكة حيوان بري في الصحراء.' },
  'blanford-s-fox': { name: 'ثعلب بلانفورد', description: 'ثعلب بلانفورد حيوان بري في آسيا.' },
  'r-ppell-s-fox': { name: 'ثعلب روبيل', description: 'ثعلب روبيل حيوان بري في أفريقيا وآسيا.' },
  'corsac-fox': { name: 'ثعلب كورساك', description: 'ثعلب كورساك حيوان بري في آسيا.' },
  'ussuri-brown-bear': { name: 'دب بني أوسوري', description: 'الدب البني الأوسوري حيوان بري في روسيا.' },
  'kodiak-bear': { name: 'دب كودياك', description: 'دب كودياك حيوان بري في أمريكا الشمالية.' },
  'gobi-bear': { name: 'دب غوبي', description: 'الدب الغوبي حيوان بري في منغوليا.' },
  'syrian-brown-bear': { name: 'دب بني سوري', description: 'الدب البني السوري حيوان بري في الشرق الأوسط.' },
  'atlantic-walrus': { name: 'فول أطلسي', description: 'الفول الأطلسي حيوان بري بحري.' },
  'pacific-walrus': { name: 'فول محيطي', description: 'الفول المحيطي حيوان بري بحري.' },
  'northern-fur-seal': { name: 'فقمة فراء شمالي', description: 'فقمة الفراء الشمالي حيوان بري بحري.' },
  'guadalupe-fur-seal': { name: 'فقمة فراء غوادلوب', description: 'فقمة الفراء غوادلوب حيوان بري بحري.' },
  'new-zealand-sea-lion': { name: 'أسد بحري نيوزيلندي', description: 'الأسد البحري النيوزيلندي حيوان بري بحري.' },
  'galapagos-sea-lion': { name: 'أسد بحري غالاباغوس', description: 'الأسد البحري غالاباغوس حيوان بري بحري.' },
  'south-american-sea-lion': { name: 'أسد بحري جنوب أمريكي', description: 'الأسد البحري الجنوبي الأمريكي حيوان بري بحري.' },
  'australian-sea-lion': { name: 'أسد بحري أسترالي', description: 'الأسد البحري الأسترالي حيوان بري بحري.' },
  'antarctic-fur-seal': { name: 'فقمة فراء قطبي جنوبي', description: 'فقمة الفراء القطبي الجنوبي حيوان بري بحري.' },
  'subantarctic-fur-seal': { name: 'فقمة فراء شبه قطبي جنوبي', description: 'فقمة الفراء شبه القطبي الجنوبي حيوان بري بحري.' },
  'pangolin': { name: 'بغل', description: 'البغل حيوان بري بجلد متصلب.' },
  'black-footed-ferret': { name: 'قندس أسود القدم', description: 'القندس الأسود القدم حيوان بري في أمريكا الشمالية.' },
  'steppe-polecat': { name: 'قندس سهبي', description: 'القندس السهبي حيوان بري في آسيا.' },
  'yellow-throated-marten': { name: 'مارتن أصفر الحلق', description: 'المارتن أصفر الحلق حيوان بري في آسيا.' },
  'marbled-polecat': { name: 'قندس رخامي', description: 'القندس الرخامي حيوان بري في آسيا.' },
  'least-weasel': { name: ' Floor', description: 'Floor حيوان بري صغير.' },
  'long-tailed-weasel': { name: ' Floor طويل الذيل', description: 'Floor طويل الذيل حيوان بري صغير.' },
  'greater-sheathbill': { name: 'أوز غطاء أكبر', description: 'أوز الغطاء الأكبر حيوان بري في أمريكا الجنوبية.' },
  'yellow-eyed-panda': { name: 'باندا صفراء العيون', description: 'الباندا صفراء العيون حيوان بري في الصين.' },
  'tibetan-fox': { name: 'ثعلب تيتي', description: 'الثعلب التيتي حيوان بري في آسيا.' },
  'pale-fox': { name: 'ثعلب شاحب', description: 'الثعلب الشاحب حيوان بري في أفريقيا.' },
  'crab-eating-fox': { name: 'ثعلب آكل السرطان', description: 'الثعلب آكل السرطان حيوان بري في أمريكا الجنوبية.' },
  'short-eared-dog': { name: 'كلب قصير الأذن', description: 'الكلب قصير الأذن حيوان بري في أمريكا الجنوبية.' },
  'bush-dog': { name: 'كلب شجري', description: 'الكلب الشجري حيوان بري في أمريكا الجنوبية.' },
  'sechuran-fox': { name: 'ثعلب سيتشورا', description: 'الثعلب السيتشوري حيوان بري في أمريكا الجنوبية.' },
  'darwin-s-fox': { name: 'ثعلب داروين', description: 'الثعلب الدارويني حيوان بري في أمريكا الجنوبية.' },
  'hoary-fox': { name: 'ثعلب رمادي', description: 'الثعلب الرمادي حيوان بري في أمريكا الجنوبية.' },
  'silver-fox': { name: 'ثعلب فضي', description: 'الثعلب الفضي حيوان بري.' },
  'siamese-fox': { name: 'ثعلب سيامي', description: 'الثعلب السيامي حيوان بري في آسيا.' },
  'kit-fox': { name: 'ثعلب صغير', description: 'الثعلب الصغير حيوان بري في أمريكا الشمالية.' },
  'swift-fox': { name: 'ثعلب سريع', description: 'الثعلب السريع حيوان بري في أمريكا الشمالية.' },
  'serengeti-fox': { name: 'ثعلب سيرينغيتي', description: 'الثعلب السيرينغيتي حيوان بري في أفريقيا.' },
  'gray-fox': { name: 'ثعلب رمادي', description: 'الثعلب الرمادي حيوان بري في أمريكا الشمالية.' },
  'earless-fox': { name: 'ثعلب بلا أذن', description: 'الثعلب بلا أذن حيوان بري في أفريقيا.' },
  'big-eared-fox': { name: 'ثعلب كبير الأذن', description: 'الثعلب كبير الأذن حيوان بري في أمريكا الجنوبية.' },
  'island-fox': { name: 'ثเกาะ', description: 'الثعلب الجزري حيوان بري في أمريكا الشمالية.' },
  'koslov-s-fox': { name: 'ثعلب كوسلاف', description: 'الثعلب الكوسلافي حيوان بري في آسيا.' },
  'bat-eared-foxes': { name: 'ثعالب بأذني خفاش', description: 'الثعالب بأذني خفاش حيوان بري في أفريقيا.' },
  'saharan-fox': { name: 'ثعلب صحراوي', description: 'الثعلب الصحراوي حيوان بري في أفريقيا.' },
  'indian-fox': { name: 'ثعلب هندي', description: 'الثعلب الهندي حيوان بري في الهند.' },
  'persian-fox': { name: 'ثعلب فارسي', description: 'الثعلب الفارسي حيوان بري في آسيا.' },
  'bengal-fox': { name: 'ثعلب بنغالي', description: 'الثعلب البنغالي حيوان بري في الهند.' },
  'ugandan-fox': { name: 'ثعلب أوغندي', description: 'الثعلب الأوغندي حيوان بري في أفريقيا.' },
  'tundra-fox': { name: 'ثعلب توندرا', description: 'الثعلب التوندري حيوان بري في القطب الشمالي.' },
  'mountain-fox': { name: 'ثعلب جبلي', description: 'الثعلب الجبلي حيوان بري في الجبال.' },
  'cozumel-fox': { name: 'ثعلب كوزومل', description: 'الثعلب الكوزوملي حيوان بري في أمريكا الشمالية.' },
  'gracile-fox': { name: 'ثعلب رشيق', description: 'الثعلب الرشيق حيوان بري في أمريكا الجنوبية.' },
  'simien-fox': { name: 'ثعلب سيمين', description: 'الثعلب السيميني حيوان بري في أفريقيا.' },
  'javan-rhinoceros': { name: 'وحيد القرن Jáv', description: 'وحيد القرن Jáv حيوان بري في آسيا.' },
  'sumatran-rhinoceros': { name: 'وحيد القرن سوماترا', description: 'وحيد القرن السوماتري حيوان بري في آسيا.' },
  'indian-rhinoceros': { name: 'وحيد القرن الهندي', description: 'وحيد القرن الهندي حيوان بري في الهند.' },
  'himalayan-tahr': { name: 'تاهور هيمالايا', description: 'التاهور الهيمالايا حيوان بري في الجبال.' },
  'markhor': { name: 'مارخور', description: 'المارخور حيوان بري في آسيا.' },
  'blue-sheep': { name: 'خروف أزرق', description: 'الخروف الأزرق حيوان بري في الجبال.' },
  'barbary-sheep': { name: 'خروف بربري', description: 'الخروف البربري حيوان بري في أفريقيا.' },
  'musk-deer': { name: 'غزال المسك', description: 'غزال المسك حيوان بري في آسيا.' },
  'tufted-deer': { name: 'غزال مُدبّب', description: 'الغزال المُدبّب حيوان بري في آسيا.' },
  'muntjac': { name: 'منجاك', description: 'المنجاك حيوان بري في آسيا.' },
  'reeves-s-muntjac': { name: 'منجاك ريفز', description: 'المنجاك الريفي حيوان بري في آسيا.' },
  'chinese-water-deer': { name: 'غزال مائي صيني', description: 'الغزال المائي الصيني حيوان بري في الصين.' },
  'pere-david-s-deer': { name: 'غزال ديفيد', description: 'غزال ديفيد حيوان بري في الصين.' },
  'sika-deer': { name: 'غزال سيكا', description: 'غزال السيكا حيوان بري في آسيا.' },
  'fallow-deer': { name: 'غزال شمالي', description: 'الغزال الشمالي حيوان بري في أوروبا.' },
  'red-deer': { name: 'غزال أحمر', description: 'الغزال الأحمر حيوان بري في أوروبا.' },
  'reindeer': { name: 'رنة', description: 'الرنة حيوان بري في القطب الشمالي.' },
  'elk': { name: ' elk', description: 'ال elk حيوان بري في أمريكا الشمالية.' },
  'sambar-deer': { name: 'غزال سامبار', description: 'غزال السامبار حيوان بري في آسيا.' },
  'rusa-deer': { name: 'غزال روسا', description: 'غزال الروسا حيوان بري في آسيا.' }
};

const missing = getMissing('ar');
console.log(`ar missing: ${missing.length}`);

// Generate translations
const arNames = {};
for (const animal of missing) {
  const arName = arTranslations[animal.id] || animal.name;
  const arDesc = `${arName} حيوان. ${animal.description}`;
  arNames[animal.id] = { name: arName, description: arDesc };
}

// Write to file
const outputFile = path.join(dataDir, 'ar-names.json');
fs.writeFileSync(outputFile, JSON.stringify(arNames, null, 2));
console.log(`Generated ${Object.keys(arNames).length} ar translations`);
console.log(`Output: ${outputFile}`);
