const fs = require('fs');
const path = require('path');

const dataDir = path.join(__dirname, 'src', 'data');
const animals = JSON.parse(fs.readFileSync(path.join(dataDir, 'animals.json'), 'utf8'));
const translations = JSON.parse(fs.readFileSync(path.join(dataDir, 'animal-translations.json'), 'utf8'));

function hasNameAndDesc(entry) {
  return entry && entry.name && entry.description;
}

function getMissing(locale) {
  const localeData = translations[locale] || {};
  return animals.filter(a => !hasNameAndDesc(localeData[a.id]));
}

// Comprehensive German translations
const deTranslations = {
  // Mammals
  'african-elephant': { name: 'Afrikanischer Elefant', description: 'Der Afrikanische Elefant ist das größte lebende Landtier, bekannt für seine enorme Größe, seinen Rüssel und seine beeindruckenden Stoßzähne.' },
  'asian-elephant': { name: 'Asiatischer Elefant', description: 'Der Asiatische Elefant ist kleiner als sein afrikanischer Verwandter, mit kleineren Ohren und einem gewölbteren Kopf.' },
  'white-rhinoceros': { name: 'Breitmaulnashorn', description: 'Das Breitmaulnashorn ist die größte der fünf Nashornarten, bekannt für seinen breiten Mund und sein sanftes Wesen.' },
  'black-rhinoceros': { name: 'Spitzmaulnashorn', description: 'Das Spitzmaulnashorn ist ein Laubfresser mit gehakter Oberlippe, bekannt für sein aggressives Temperament.' },
  'hippopotamus': { name: 'Nilpferd', description: 'Das Nilpferd ist ein großes halb-aquatisches Säugetier, das den Tag hauptsächlich im Wasser verbringt, um kühl zu bleiben.' },
  'giraffe': { name: 'Giraffe', description: 'Die Giraffe ist das größte lebende Landtier und erreicht hohe Äste mit ihrem langen Hals.' },
  'okapi': { name: 'Okapi', description: 'Das Okapi ist ein scheuer Wald bewohner und ein Verwandter der Giraffe mit markanten gestreiften Beinen.' },
  'cape-buffalo': { name: 'Kap-Büffel', description: 'Der Kap-Büffel ist ein großer Büffel, bekannt für sein unberechenbares Wesen und seine massiven, gebogenen Hörner.' },
  'american-bison': { name: 'Amerikanischer Bison', description: 'Der Amerikanische Bison ist das größte Landtier Nordamerikas und zog einst in großen Herden über die Great Plains.' },
  'water-buffalo': { name: 'Wasserbüffel', description: 'Der Wasserbüffel ist ein großer Büffel, der in Asien weit verbreitet in der Landwirtschaft eingesetzt wird.' },
  'yak': { name: 'Yak', description: 'Das Yak ist ein langhaariges Rind, das an die Höhen des Himalayas angepasst ist.' },
  'domestic-cattle': { name: 'Rind', description: 'Rinder sind große Huftiere, die für Fleisch, Milch und Leder gehalten werden.' },
  'gaur': { name: 'Gaur', description: 'Der Gaur ist die größte wilde Rinderart, beheimatet in Süd- und Südostasien.' },
  'saiga-antelope': { name: 'Saiga-Antilope', description: 'Die Saiga-Antilope ist für ihre ungewöhnliche, aufgeblasene Nase bekannt, die Staub filtert und kalte Luft erwärmt.' },
  'addax': { name: 'Addax', description: 'Das Addax ist eine kritisch gefährdete Antilope, die an das Leben in der Sahara angepasst ist.' },
  'oryx': { name: 'Oryx', description: 'Das Oryx ist eine große Antilope mit langen, geraden Hörnern, die an aride Umgebungen angepasst ist.' },
  'tiger': { name: 'Tiger', description: 'Der Tiger ist die größte lebende Katzenart mit markantem orangefarbenem Fell und schwarzen Streifen.' },
  'lion': { name: 'Löwe', description: 'Der Löwe ist die einzige soziale Großkatze, die in Gruppen namens Rudel lebt.' },
  'leopard': { name: 'Leopard', description: 'Der Leopard ist eine kraftvolle, wendige Großkatze, bekannt für ihr rosettenmusteriges Fell.' },
  'snow-leopard': { name: 'Schneeleopard', description: 'Der Schneeleopard ist eine einsame Großkatze, die in den kühlen, bergigen Regionen Zentralasiens lebt.' },
  'jaguar': { name: 'Jaguar', description: 'Der Jaguar ist eine kompakte, muskulöse Katze mit einem kraftvollen Biss, der Panzerschildkröten durchbeißen kann.' },
  'cheetah': { name: 'Gepard', description: 'Der Gepard ist das schnellste Landtier, gebaut für Geschwindigkeit mit einem leichten Körper und langen Beinen.' },
  'cougar': { name: 'Puma', description: 'Der Puma ist eine große Katze, die in Amerika beheimatet ist und unter vielen Namen bekannt ist, einschließlich Berglöwe und Puma.' },
  'clouded-leopard': { name: 'B Nebenleopard', description: 'Der Nebenleopard ist eine mittelgroße Katze mit markanten wolkigen Flecken und außergewöhnlich langen Eckzähnen.' },
  'serval': { name: 'Serval', description: 'Das Serval ist eine mittelgroße Katze mit langen Beinen und großen Ohren, die in afrikanischen Grasland lebt.' },
  'caracal': { name: 'Caracal', description: 'Das Caracal ist eine mittelgroße Katze mit markanten schwarzen Ohrspitzen und ausgezeichneten Sprungfähigkeiten.' },
  'pallas-s-cat': { name: 'Manul', description: 'Das Manul ist eine kleine Katze mit flachem Gesicht und dickem Fell, die in Zentralasien lebt.' },
  'sand-cat': { name: 'Wüstenkatze', description: 'Die Wüstenkatze ist die einzige Katze, die in echten Wüsten lebt, mit speziellen Pfoten für Sand.' },
  'fishing-cat': { name: 'Fischkatze', description: 'Die Fischkatze ist eine mittelgroße Katze, die gut zum Fischen geeignet ist, mit teilweise webschen Zehen und wasserabweisendem Fell.' },
  'brown-bear': { name: 'Braunbär', description: 'Der Braunbär ist ein großes Raubtier, das weit verbreitet ist, von Nordamerika bis Eurasien.' },
  'grizzly-bear': { name: 'Grizzlybär', description: 'Der Grizzlybär ist eine Unterart des Braunbären, bekannt für den Muskelwulst an seinen Schultern und seine Aggressivität.' },
  'polar-bear': { name: 'Eisbär', description: 'Der Eisbär ist das größte fleischfressende Landtier, angepasst an die extreme Kälte der Arktis.' },
  'american-black-bear': { name: 'Amerikanischer Schwarzbär', description: 'Der Amerikanische Schwarzbär ist der häufigste Bär Nordamerikas und sehr anpassungsfähig.' },
  'asian-black-bear': { name: 'Asiatischer Schwarzbär', description: 'Der Asiatische Schwarzbär, auch Mondbär genannt, hat ein weißes V-förmiges Brustmal und lebt in asiatischen Wäldern.' },
  'spectacled-bear': { name: 'Brillenbär', description: 'Der Brillenbär ist der einzige Bär Südamerikas mit markanten Brillenflecken im Gesicht.' },
  'sun-bear': { name: 'Sonnenbär', description: 'Der Sonnenbär ist der kleinste Bär der Welt mit einem goldgelben U-förmigen Brustmal.' },
  'sloth-bear': { name: 'Höhlbär', description: 'Der Höhlbär ist ein großer insektenfressender Bär mit langem, weichem Fell und einzigartiger Ernährung.' },
  'giant-panda': { name: 'Riesenpanda', description: 'Der Riesenpanda ist Chinas Nationaltier, ernährt sich hauptsächlich von Bambus und hat ein markantes schwarz-weißes Fell.' },
  'andean-bear': { name: 'Andenbär', description: 'Der Andenbär ist der einzige Bär Südamerikas, auch Brillenbär genannt.' },
  'gray-wolf': { name: 'Wolf', description: 'Der Wolf ist das größte wilde Caniden und lebt in sozialen Rudeln.' },
  'arctic-wolf': { name: 'Arktischer Wolf', description: 'Der Arktische Wolf ist eine Unterart des Wolfs, angepasst an die extreme Kälte der Arktis.' },
  'red-fox': { name: 'Rotfuchs', description: 'Der Rotfuchs ist die am weitesten verbreitete Fuchsart mit rotbraunem Fell und buschigem Schwanz.' },
  'fennec-fox': { name: 'Fennek', description: 'Das Fennek ist der kleinste Fuchs der Welt mit unverhältnismäßig großen Ohren zur Kühlung und Wahrnehmung.' },
  'arctic-fox': { name: 'Arktischer Fuchs', description: 'Der Arktische Fuchs ist an die polare Umgebung angepasst, im Winter weiß und im Sommer braun.' },
  'african-wild-dog': { name: 'Afrikanischer Wildhund', description: 'Der Afrikanische Wildhund ist ein effizienter Rudeljäger mit markantem geflecktem Fell und großen runden Ohren.' },
  'coyote': { name: 'Kojote', description: 'Der Kojote ist ein häufiges Canid Nordamerikas mit außergewöhnlicher Anpassungsfähigkeit.' },
  'jackal': { name: 'Schakal', description: 'Der Schakal ist ein mittelgroßes Canid, das in Afrika und Asien lebt und ein Gelegenheitsfresser ist.' },
  'dingo': { name: 'Dingo', description: 'Das Dingo ist ein wilder Hund Australiens, möglicherweise vor Tausenden von Jahren vom Menschen eingeführt.' },
  'maned-wolf': { name: 'Mähnenwolf', description: 'Der Mähnenwolf ist das größte Canid Südamerikas mit markantem rotbraunem Fell und langen Beinen.' },
  'western-gorilla': { name: 'Westlicher Gorilla', description: 'Der Westliche Gorilla ist das größte Primat und lebt in den Regenwäldern Zentralafrikas.' },
  'eastern-gorilla': { name: 'Östlicher Gorilla', description: 'Der Östliche Gorilla ist das größte lebende Primat und lebt in den Bergwäldern Ostafrikas.' },
  'chimpanzee': { name: 'Schimpansen', description: 'Der Schimpansen ist eines der nächsten Verwandten des Menschen mit komplexer sozialer Struktur und Werkzeuggebrauch.' },
  'bonobo': { name: 'Bonobo', description: 'Der Bonobo ähnelt dem Schimpansen, ist aber kleiner und für seine friedliche Gesellschaft bekannt.' },
  'orangutan': { name: 'Orang-Utan', description: 'Der Orang-Utan ist der größte Affe Asiens mit rotbraunem Fell, der hauptsächlich in Bäumen lebt.' },
  'siamang': { name: 'Siamang', description: 'Der Siamang ist der größte Gibbon mit markantem Kehlsack, der laute Rufe ausstoßen kann.' },
  'gibbon': { name: 'Gibbon', description: 'Der Gibbon ist ein kleiner Affe, bekannt für sein exzellentes Schwingen und melodischen Gesang.' },
  'mandrill': { name: 'Mandrill', description: 'Der Mandrill ist der größte Affe, Männchen haben leuchtend blaue und rote Gesichter.' },
  'proboscis-monkey': { name: 'Nasenaffe', description: 'Der Nasenaffe ist für seine große Nase bekannt und lebt in den Mangroven und Uferwäldern Borneos.' },
  'spider-monkey': { name: 'Spider-Affe', description: 'Der Spider-Affe hat lange, geschmeidige Gliedmaßen und kann sich geschickt zwischen den Bäumen schwingen.' },
  'capuchin-monkey': { name: 'Kapuzineraffe', description: 'Der Kapuzineraffe ist ein intelligenter Affe, der Werkzeuge benutzt und in den Wäldern Mittel- und Südamerikas lebt.' },
  'lemur': { name: 'Lemur', description: 'Der Lemur ist ein endemisches Primat Madagaskars mit großen Augen und langem Schwanz.' },
  'indri': { name: 'Indri', description: 'Der Indri ist der größte Lemur mit markantem Ruf und lebt in den Regenwäldern Madagaskars.' },
  'tarsier': { name: 'Tarsier', description: 'Der Tarsier ist eines der kleinsten Primaten mit unverhältnismäßig großen Augen.' },
  'aye-aye': { name: 'Aye-aye', description: 'Das Aye-aye ist ein einzigartiger Lemur mit langem, dünnem Mittelfinger zum Abklopfen von Stämmen auf Insekten.' },
  'blue-whale': { name: 'Blauwal', description: 'Der Blauwal ist das größte Tier, das jemals auf der Erde gelebt hat, mit einem Herzen von der Größe eines Kleinwagens.' },
  'humpback-whale': { name: 'Buckelwal', description: 'Der Buckelwal ist bekannt für seinen komplexen Gesang und das Springen aus dem Wasser.' },
  'sperm-whale': { name: 'Pottwal', description: 'Der Pottwal ist der größte Zahnwal und kann in die Tiefe tauchen, um Riesenfische zu jagen.' },
  'killer-whale': { name: 'Schwertwal', description: 'Der Schwertwal ist der Top-Räuber der Ozeane mit schwarz-weißem Fell und komplexer sozialer Struktur.' },
  'bottlenose-dolphin': { name: 'Großer Tümmler', description: 'Der Große Tümmler ist der bekannteste Delfin, bekannt für seine Intelligenz und Freundlichkeit.' },
  'narwhal': { name: 'Narwal', description: 'Das Narwal hat einen langen, spiralförmigen Stupser und wird als "Einhorn des Meeres" bezeichnet.' },
  'beluga-whale': { name: 'Beluga', description: 'Der Beluga ist der einzige weiße Wal, bekannt für seine "Gesangsfähigkeiten".' },
  'manatee': { name: 'Manati', description: 'Das Manati ist ein sanftes, großes Wasser-Säugetier, das sich von Wasserpflanzen ernährt und als "Meerjungfrau" bezeichnet wird.' },
  'dugong': { name: 'Dugong', description: 'Der Dugong ist ein großes marinTier, ähnlich dem Manati, hauptsächlich im Indischen und Pazifischen Ozean verbreitet.' },
  'walrus': { name: 'Walross', description: 'Das Walross hat lange Stößel und dicke Haut und lebt in der Arktis.' },
  'elephant-seal': { name: 'Elefantenrobbe', description: 'Die Elefantenrobbe ist die größte Robbenart, Männchen haben eine große Nase.' },
  'leopard-seal': { name: 'Leopardrobbe', description: 'Die Leopardrobbe ist der Top-Räuber der Antarktis mit kraftvollen Kiefern und gepunktetem Fell.' },
  'harp-seal': { name: 'Bandrobbe', description: 'Die Bandrobbe hat ein markantes harpenförmiges Muster und lebt im Nordatlantik.' },
  'sea-otter': { name: 'Seeotter', description: 'Der Seeotter ist das einzige Meeressäugetier, das häufig Werkzeuge benutzt, um Muscheln zu öffnen.' },
  'hawaiian-monk-seal': { name: 'Hawaiische Monkrobbe', description: 'Die Hawaiische Monkrobbe ist eine endemische Robbenart Hawaiis und stark gefährdet.' },
  'steller-sea-lion': { name: 'Steller-Seelöwe', description: 'Der Steller-Seelöwe ist eine Robbe mit äußeren Ohrmuscheln, die mit ihren Flossen an Land laufen kann.' },
  'capybara': { name: 'Capibara', description: 'Die Capibara ist das größte Nager der Welt und lebt in Südamerika an Gewässern.' },
  'beaver': { name: 'Biber', description: 'Der Biber ist ein geschickter Baumeister, der Dämme und Burgen aus Ästen und Schlamm bauen kann.' },
  'porcupine': { name: 'Stachelschwein', description: 'Das Stachelschwein ist mit scharfen Stacheln bedeckt, die als Abwehr gegen Raubtiere dienen.' },
  'crested-porcupine': { name: 'Kronen-Stachelschwein', description: 'Das Kronen-Stachelschwein ist die größte Stachelschweinart mit langen, spitzen Stacheln.' },
  'naked-mole-rat': { name: ' Nacktmull', description: 'Der Nacktmull ist das einzige bekannte eusoziale Säugetier und lebt in unterirdischen Tunneln.' },
  'prairie-dog': { name: 'Prairiehund', description: 'Der Prairiehund ist ein sozialer Nager, der komplexe Rufe zur Warnung seiner Gefährten ausstoßen kann.' },
  'squirrel': { name: 'Eichhörnchen', description: 'Das Eichhörnchen ist ein kleiner Nager mit buschigem Schwanz, der gut auf Bäume klettern kann.' },
  'chinchilla': { name: 'Chinchilla', description: 'Das Chinchilla hat ein außergewöhnlich weiches Fell mit über 20.000 Haaren pro Quadratzentimeter.' },
  'guinea-pig': { name: 'Meerschweinchen', description: 'Das Meerschweinchen ist ein sanftes, soziales Nagetier, das weit verbreitet als Haustier gehalten wird.' },
  'hamster': { name: 'Hamster', description: 'Der Hamster ist ein kleines, nachtaktives Nagetier mit aufgeblähten Backentaschen zur Nahrungsspeicherung.' },
  'mouse': { name: 'Maus', description: 'Die Maus ist ein kleines Nagetier mit außergewöhnlicher Anpassungsfähigkeit, das in verschiedenen Umgebungen leben kann.' },
  'rat': { name: 'Ratte', description: 'Die Ratte ist ein großes Nagetier mit langem, haarlosem Schwanz und ist ein intelligentes, soziales Tier.' },
  'indian-flying-fox': { name: 'Indischer Flughund', description: 'Der Indische Flughund ist einer der größten Fledermäuse der Welt mit enormer Flügelspannweite.' },
  'little-brown-bat': { name: 'Kleines braunes Fledermaus', description: 'Das Kleine braune Fledermaus ist eine häufige Fledermausart Nordamerikas, die sich von Insekten ernährt.' },
  'mexican-free-tailed-bat': { name: 'Mexikanische freischwänzige Fledermaus', description: 'Die Mexikanische freischwänzige Fledermaus ist eine der zahlreichsten Säugetiere der Welt.' },
  'fruit-bat': { name: 'Flughund', description: 'Der Flughund ernährt sich von Früchten und Nektar und hat ein gutes Sehvermögen statt Echoortung.' },
  'horseshoe-bat': { name: 'Hufeisennasenfledermaus', description: 'Die Hufeisennasenfledermaus hat markante Blätter an der Nase zur Echoortung und lebt hauptsächlich in Asien und Afrika.' },
  'vampire-bat': { name: 'Vampirfledermaus', description: 'Die Vampirfledermaus ist das einzige Säugetier, das sich von Blut ernährt und in Mittel- und Südamerika lebt.' },
  'megabat': { name: 'Große Fledermaus', description: 'Große Fledermäuse umfassen Flughunde und Große Fledermäuse mit größerer Körpergröße und gutem Sehvermögen.' },
  'red-kangaroo': { name: 'Rotes Riesenkänguru', description: 'Das Rote Riesenkänguru ist das größte Beuteltier und kann Geschwindigkeiten über 56 km/h springen.' },
  'grey-kangaroo': { name: 'Graues Riesenkänguru', description: 'Das Graue Riesenkänguru ist ein häufiges großes Känguru Australiens, das in verschiedenen Umgebungen lebt.' },
  'wallaby': { name: 'Wallaby', description: 'Das Wallaby ist ein kleines Känguru, das hauptsächlich in Australien und Neuguinea vorkommt.' },
  'tree-kangaroo': { name: 'Baumkänguru', description: 'Das Baumkänguru ist ein an das Leben in Bäumen angepasstes Känguru mit kürzeren Hinterbeinen und langem Schwanz.' },
  'quokka': { name: 'Quokka', description: 'Das Quokka wird als "glücklichstes Tier der Welt" bezeichnet und hat ein scheinbar lächelndes Gesicht.' },
  'wombat': { name: 'Wombat', description: 'Das Wombat ist ein stockiges Beuteltier Australiens mit quadratischem Kot.' },
  'koala': { name: 'Koala', description: 'Der Koala ist das Wahrzeichen Australiens, ernährt sich von Eukalyptusblättern und schläft über 18 Stunden am Tag.' },
  'tasmanian-devil': { name: 'Tasmanischer Teufel', description: 'Der Tasmanische Teufel ist ein endemisches fleischfressendes Beuteltier Tasmaniens mit kraftvollen Kiefern.' },
  'quoll': { name: 'Quoll', description: 'Das Quoll ist ein mittelkleines fleischfressendes Beuteltier mit weißen Flecken, das in Australien und Neuguinea lebt.' },
  'numbat': { name: 'Numbat', description: 'Das Numbat ist das einzige tagsaktive fleischfressende Beuteltier, das sich von Termiten ernährt.' },
  'bandicoot': { name: 'Bandicoot', description: 'Das Bandicoot ist ein kleines, allesfressendes Beuteltier mit langer Nase und kurzem Schwanz.' },
  'sugar-glider': { name: 'Zuckergleiter', description: 'Der Zuckergleiter ist ein kleines Beuteltier mit Membranen, das zwischen Bäumen gleiten kann.' },
  'possum': { name: 'Beutelratte', description: 'Die Beutelratte ist ein kleines Beuteltier mit gekräuseltem Schwanz, das an Ästen hängen kann.' },
  'badger': { name: 'Dachs', description: 'Der Dachs ist ein fleischfressendes Tier mit schwarz-weiß gestreiftem Gesicht, das in unterirdischen Bauten lebt.' },
  'fisher': { name: 'Fisher', description: 'Der Fisher ist ein mittelkleines Marder, das in den Wäldern Nordamerikas lebt.' },
  'pine-marten': { name: 'Baummarder', description: 'Der Baummarder ist ein kleiner Marder mit braunem Fell und cremefarbener Kehle.' },
  'stoat': { name: 'Hermelin', description: 'Das Hermelin ist ein kleiner Marder, der im Winter weiß und im Sommer braun wird.' },
  'weasel': { name: 'Wiesel', description: 'Das Wiesel ist ein fleischfressendes Tier mit schlankem Körper, das in kleine Räume eindringen kann.' },
  'european-polecat': { name: 'Europäischer Iltis', description: 'Der Europäische Iltis ist ein mittelgroßer Marder mit schwarz-weiß gestreiftem Gesicht.' },
  'mink': { name: 'Mink', description: 'Der Mink ist ein halb-aquatiles Marder mit wasserabweisendem, dickem Fell.' },
  'coati': { name: 'Nasenbär', description: 'Der Nasenbär ist ein Waschbär mit langer, geschickter Nase und langem Schwanz.' },
  'kinkajou': { name: 'Honigbär', description: 'Der Honigbär ist ein tropischer Waschbär mit kräuselbarem Schwanz.' },
  'hedgehog': { name: 'Igel', description: 'Der Igel ist mit scharfen Stacheln bedeckt und rollt sich bei Gefahr zu einer Kugel zusammen.' },
  'tenrec': { name: 'Tenrek', description: 'Das Tenrek ist ein endemisches Insektenfresser Madagaskars, das dem Igel ähnlich sieht.' },
  'shrew': { name: 'Spitzmaus', description: 'Die Spitzmaus ist ein kleines Insektenfresser mit spitzer Nase und schnellem Stoffwechsel.' },
  'star-nosed-mole': { name: 'Sternmole', description: 'Die Sternmole hat eine markante sternenförmige Nase zum Aufspüren von Beute unter der Erde.' },
  'golden-mole': { name: 'Goldmulle', description: 'Die Goldmulle ist ein afrikanischer unterirdischer Insektenfresser mit goldenem Fell und zurückgebildeten Augen.' },
  'solenodon': { name: 'Solenodon', description: 'Das Solenodon ist ein urtümlicher Insektenfresser der Karibik mit Gift.' },
  'elephant-shrew': { name: 'Elefantenspitzmaus', description: 'Die Elefantenspitzmaus hat einen langen, geschickten Rüssel, der an den eines Elefanten erinnert, und lebt in Afrika.' },
  'chinese-pangolin': { name: 'Chinesisches Schuppentier', description: 'Das Chinesische Schuppentier ist mit Schuppen bedeckt und ernährt sich von Ameisen und Termiten, stark gefährdet.' },
  'sunda-pangolin': { name: 'Sunda-Schuppentier', description: 'Das Sunda-Schuppentier ist eine Schuppentierart Südostasiens, stark gefährdet.' },
  'indian-pangolin': { name: 'Indisches Schuppentier', description: 'Das Indische Schuppentier kommt in Südasiens vor und hat große Schuppen.' },
  'white-bellied-pangolin': { name: 'Weißbauch-Schuppentier', description: 'Das Weißbauch-Schuppentier kommt in Zentralafrika vor und hat einen weißen Bauch.' },
  'giant-pangolin': { name: 'Riesenschuppentier', description: 'Das Riesenschuppentier ist die größte Schuppentierart und lebt in Afrika.' },
  'giant-armadillo': { name: 'Riesen-Gürteltier', description: 'Das Riesen-Gürteltier ist die größte Gürteltierart mit massivem Panzer.' },
  'nine-banded-armadillo': { name: 'Nordgürteltier', description: 'Das Nordgürteltier ist das einzige Gürteltier, das springen kann, und kommt in Amerika vor.' },
  'pink-fairy-armadillo': { name: 'Pinker-Zwerg-Gürteltier', description: 'Das Pink-Zwerg-Gürteltier ist das kleinste Gürteltier mit rosa Panzer.' },
  'southern-three-banded-armadillo': { name: 'Dreibinden-Gürteltier', description: 'Das Dreibinden-Gürteltier kann sich zu einer Kugel zusammenrollen.' },
  'giant-anteater': { name: 'Riesenameisenbär', description: 'Der Riesenameisenbär hat eine lange Zunge und kann große Mengen Ameisen auflecken.' },
  'two-toed-sloth': { name: 'Zweifinger-Faultier', description: 'Das Zweifinger-Faultier ist eines der langsamsten Säugetiere und verbringt die meiste Zeit kopfüber in Bäumen.' },
  'southern-tamandua': { name: 'Südlicher Tamandua', description: 'Der Südliche Tamandua ist ein mittelgroßer Ameisenbär mit teilweise baumbewohnender Lebensweise.' },
  'aardvark': { name: 'Erdferkel', description: 'Das Erdferkel hat lange Ohren und eine lange Nase und ernährt sich von Ameisen und Termiten in Afrika.' },
  'bat-eared-fox': { name: 'Fennek', description: 'Der Fennek hat unverhältnismäßig große Ohren, um unterirdische Insekten zu hören.' },
  'fossa': { name: 'Fossa', description: 'Die Fossa ist das größte Raubtier Madagaskars, similar to a Mungo.' },
  'aardwolf': { name: 'Erdwolf', description: 'Der Erdwolf ist ein kleines Hyänenartiges Tier, das sich von Termiten ernährt.' },
  'spotted-hyena': { name: 'Tüpfelhyäne', description: 'Die Tüpfelhyäne ist die häufigste Hyäne Afrikas mit kraftvollen Kiefern und sozialem Verhalten.' },
  'striped-hyena': { name: 'Streifenhyäne', description: 'Die Streifenhyäne hat ein gestreiftes Fell und eine Buschmähne und kommt in Afrika und Asien vor.' },
  'martens': { name: 'Marder', description: 'Der Marder ist ein kleines Raubtier mit schlankem Körper und weichem Fell.' },
  'sable': { name: 'Zobelmarder', description: 'Der Zobelmarder hat dunkles Fell und ist ein wertvolles Pelztier.' },
  'hog-badger': { name: 'Schweinsdachs', description: 'Der Schweinsdachs ist ein asiatischer Marder mit schweineartiger Nase und kräftigen Krallen.' },
  'raccoon-dog': { name: 'Waschbärhund', description: 'Der Waschbärhund ist ein Canid mit waschbärähnlichem Aussehen und stammt aus Ostasien.' },
  'crabeater-seal': { name: 'Krabbenfresserrobbe', description: 'Die Krabbenfresserrobbe ernährt sich tatsächlich von Krill und ist die häufigste Robbe der Antarktis.' },
  'weddell-seal': { name: 'Weddellrobbe', description: 'Die Weddellrobbe lebt in der Antarktis und kann bis zu 80 Minuten unter dem Eis tauchen.' },
  'ross-seal': { name: 'Rossrobbe', description: 'Die Rossrobbe ist die seltenste Robbe der Antarktis mit markantem Gesichtsausdruck.' },
  'arctic-ground-squirrel': { name: 'Arktisches Baumhörnchen', description: 'Das Arktische Baumhörnchen ist das einzige Säugetier, das seine Körpertemperatur unter den Gefrierpunkt senken kann.' },
  'nutria': { name: 'Nutria', description: 'Die Nutria ist ein großes, halb-aquatisches Nagetier aus Südamerika.' },
  'african-crested-porcupine': { name: 'Afrikanisches Stachelschwein', description: 'Das Afrikanische Stachelschwein ist die größte Stachelschweinart mit langen, spitzen Stacheln.' },
  'springhare': { name: 'Springhase', description: 'Der Springhase ist ein afrikanisches Nagetier mit langen Hinterbeinen zum Springen.' },
  'cane-rat': { name: 'Zuckerratte', description: 'Die Zuckerratte ist ein großes afrikanisches Nagetier, das sich von Pflanzen ernährt.' },
  'paca': { name: 'Paka', description: 'Die Paka ist ein großes südamerikanisches Nagetier mit weißen Streifen.' },
  'agouti': { name: 'Agouti', description: 'Das Agouti ist ein südamerikanisches Nagetier, das Samen speichern kann.' },
  'mara': { name: 'Mara', description: 'Die Mara ist ein großes südamerikanisches Nagetier mit langen Beinen und Ohren.' },
  'rock-hyrax': { name: 'Klippschliefer', description: 'Der Klippschliefer ist ein kleines Säugetier Afrikas und Asiens, ein Verwandter des Elefanten.' },
  'cape-hyrax': { name: 'Kap-Schliefer', description: 'Der Kap-Schliefer lebt im südlichen Afrika und bewohnt felsige Gebiete.' },
  'hyrax': { name: 'Schliefer', description: 'Der Schliefer ist ein Verwandter der Huftiere und sieht aus wie ein Kaninchen.' },
  'golden-moles': { name: 'Goldmulle', description: 'Goldmulle sind unterirdische afrikanische Tiere mit goldenem Fell.' },
  'elephant-shrews': { name: 'Elefantenspitzmäuse', description: 'Elefantenspitzmäuse haben lange Nasen und kommen in Afrika vor.' },
  'fennec-foxes': { name: 'Fenneks', description: 'Fenneks haben große Ohren und leben in der Sahara.' },
  'blanford-s-fox': { name: 'Blandfords Fuchs', description: 'Blandfords Fuchs lebt im Nahen Osten.' },
  'r-ppell-s-fox': { name: 'Rüppells Fuchs', description: 'Rüppells Fuchs ist ein kleiner Fuchs Afrikas und Asiens.' },
  'corsac-fox': { name: 'Steppenfuchs', description: 'Der Steppenfuchs lebt in den Steppen und Wüsten Zentralasiens.' },
  'ussuri-brown-bear': { name: 'Ussuri-Braunbär', description: 'Der Ussuri-Braunbär lebt in den Wäldern Ostasiens.' },
  'kodiak-bear': { name: 'Kodiakbär', description: 'Der Kodiakbär ist die größte Braunbärenunterart und lebt in Alaska.' },
  'gobi-bear': { name: 'Gobibär', description: 'Der Gobibär ist einer der seltensten Bären der Welt.' },
  'syrian-brown-bear': { name: 'Syrischer Braunbär', description: 'Der Syrische Braunbär lebt im Nahen Osten.' },
  'atlantic-walrus': { name: 'Atlantisches Walross', description: 'Das Atlantische Walross hat lange Stößel und lebt im Nordatlantik.' },
  'pacific-walrus': { name: 'Pazifisches Walross', description: 'Das Pazifische Walross hat lange Stößel und lebt im Nordpazifik.' },
  'northern-fur-seal': { name: 'Nördlicher Seebär', description: 'Der Nördliche Seebär ist eine gesellige Robbe, die im Nordpazifik lebt.' },
  'guadalupe-fur-seal': { name: 'Guadalupe-Seebär', description: 'Der Guadalupe-Seebär ist stark gefährdet.' },
  'new-zealand-sea-lion': { name: 'Neuseeländischer Seelöwe', description: 'Der Neuseeländische Seelöwe ist einer der seltensten Seelöwen der Welt.' },
  'galapagos-sea-lion': { name: 'Galápagos-Seelöwe', description: 'Der Galápagos-Seelöwe ist eine endemische Art der Galápagos-Inseln.' },
  'south-american-sea-lion': { name: 'Südamerikanischer Seelöwe', description: 'Der Südamerikanische Seelöwe kommt an den Küsten Südamerikas vor.' },
  'australian-sea-lion': { name: 'Australischer Seelöwe', description: 'Der Australische Seelöwe ist eine endemische Art Australiens.' },
  'antarctic-fur-seal': { name: 'Antarktischer Seebär', description: 'Der Antarktische Seebär lebt in der Antarktis.' },
  'subantarctic-fur-seal': { name: 'Subantarktischer Seebär', description: 'Der Subantarktische Seebär lebt auf den subantarktischen Inseln.' },
  'pangolin': { name: 'Schuppentier', description: 'Das Schuppentier hat Schuppen und ernährt sich von Ameisen.' },
  'black-footed-ferret': { name: 'Schwarzbxzügeltes Wiesel', description: 'Das Schwarzbxzügelte Wiesel ist das einzige heimische Wiesel Nordamerikas.' },
  'steppe-polecat': { name: 'Steppeniltis', description: 'Der Steppeniltis lebt in den Steppen Eurasiens.' },
  'yellow-throated-marten': { name: 'Gelbkehliger Baummarder', description: 'Der Gelbkehlige Baummarder ist ein asiatischer Marder mit gelber Kehle.' },
  'marbled-polecat': { name: 'Gebänderter Iltis', description: 'Der Gebänderte Iltis hat markante Gesichtsmuster.' },
  'least-weasel': { name: 'Mustelwiesel', description: 'Das Mustelwiesel ist das kleinste Raubtier der Welt.' },
  'long-tailed-weasel': { name: 'Langschwanzwiesel', description: 'Das Langschwanzwiesel hat einen langen Schwanz und kommt in Amerika vor.' },
  'greater-sheathbill': { name: 'Riesenschafhühnchen', description: 'Das Riesenschafhühnchen ist ein Vogel der Antarktis.' },
  'yellow-eyed-panda': { name: 'Kleiner Panda', description: 'Der Kleine Panda hat rotbraunes Fell und einen langen Schwanz.' },
  'tibetan-fox': { name: 'Tibetfuchs', description: 'Der Tibetfuchs hat ein markant quadratisches Gesicht und lebt auf dem Tibetischen Plateau.' },
  'pale-fox': { name: 'Blassfuchs', description: 'Der Blassfuchs ist ein kleiner afrikanischer Fuchs.' },
  'crab-eating-fox': { name: 'Krabbenfresserfuchs', description: 'Der Krabbenfresserfuchs lebt in Südamerika.' },
  'short-eared-dog': { name: 'Kurzohrhund', description: 'Der Kurzohrhund ist ein südamerikanisches Canid.' },
  'bush-dog': { name: 'Buschhund', description: 'Der Buschhund ist ein kleines südamerikanisches Canid.' },
  'sechuran-fox': { name: 'Sechura-Fuchs', description: 'Der Sechura-Fuchs lebt in Südamerika.' },
  'darwin-s-fox': { name: 'Darwins Fuchs', description: 'Darwins Fuchs ist ein endemischer Fuchs Chiles.' },
  'hoary-fox': { name: 'Graufuchs', description: 'Der Graufuchs ist ein südamerikanischer Fuchs.' },
  'silver-fox': { name: 'Silberfuchs', description: 'Der Silberfuchs ist eine schwarze Variante des Rotfuchses.' },
  'siamese-fox': { name: 'Siamesischer Fuchs', description: 'Der Siamesische Fuchs lebt in Südostasien.' },
  'kit-fox': { name: 'Kitfuchs', description: 'Der Kitfuchs ist der kleinste Fuchs Nordamerikas.' },
  'swift-fox': { name: 'Schnellfuchs', description: 'Der Schnellfuchs ist ein kleiner nordamerikanischer Fuchs.' },
  'serengeti-fox': { name: 'Serengetifuchs', description: 'Der Serengetifuchs lebt in Afrika.' },
  'gray-fox': { name: 'Graufuchs', description: 'Der Graufuchs ist ein häufiger nordamerikanischer Fuchs.' },
  'earless-fox': { name: 'Ohrenloser Fuchs', description: 'Der Ohrenlose Fuchs lebt in Afrika.' },
  'big-eared-fox': { name: 'Ohrenfuchs', description: 'Der Ohrenfuchs hat große Ohren.' },
  'island-fox': { name: 'Inselfuchs', description: 'Der Inselfuchs ist eine endemische Art der Kanalinseln Kaliforniens.' },
  'koslov-s-fox': { name: 'Koslops Fuchs', description: 'Koslops Fuchs ist eine gefährdete Art.' },
  'bat-eared-foxes': { name: 'Fenneks', description: 'Fenneks haben große Ohren und leben in Afrika.' },
  'saharan-fox': { name: 'Sahara-Fuchs', description: 'Der Sahara-Fuchs lebt in der Sahara.' },
  'indian-fox': { name: 'Indischer Fuchs', description: 'Der Indische Fuchs lebt in Südindien.' },
  'persian-fox': { name: 'Persischer Fuchs', description: 'Der Persische Fuchs lebt im Nahen Osten.' },
  'bengal-fox': { name: 'Bengalischer Fuchs', description: 'Der Bengalische Fuchs lebt im indischen Subkontinent.' },
  'ugandan-fox': { name: 'Ugandischer Fuchs', description: 'Der Ugandische Fuchs lebt in Afrika.' },
  'tundra-fox': { name: 'Tundra-Fuchs', description: 'Der Tundra-Fuchs lebt in der Arktis.' },
  'mountain-fox': { name: 'Bergfuchs', description: 'Der Bergfuchs lebt in Bergregionen.' },
  'cozumel-fox': { name: 'Cozumel-Fuchs', description: 'Der Cozumel-Fuchs lebt in Mexico.' },
  'gracile-fox': { name: 'Schlankfuchs', description: 'Der Schlankfuchs ist ein südamerikanischer Fuchs.' },
  'simien-fox': { name: 'Simien-Fuchs', description: 'Der Simien-Fuchs ist ein endemischer Fuchs Äthiopiens.' },
  'javan-rhinoceros': { name: 'Javanisches Nashorn', description: 'Das Javanische Nashorn ist eines der seltensten großen Tiere der Welt.' },
  'sumatran-rhinoceros': { name: 'Sumatranisches Nashorn', description: 'Das Sumatranische Nashorn ist die kleinste Nashornart.' },
  'indian-rhinoceros': { name: 'Indisches Nashorn', description: 'Das Indische Nashorn hat dicke Haut und ein einzelnes Horn.' },
  'himalayan-tahr': { name: 'Himalaya-Tahr', description: 'Der Himalaya-Tahr lebt in Bergregionen.' },
  'markhor': { name: 'Markhor', description: 'Der Markhor hat spiralförmige Hörner und lebt in den Bergen Zentralasiens.' },
  'blue-sheep': { name: 'Blauschaf', description: 'Das Blauschaf lebt in steilen Felsregionen.' },
  'barbary-sheep': { name: 'Barbarie-Schaf', description: 'Das Barbarie-Schaf lebt in den Bergen Nordafrikas.' },
  'musk-deer': { name: 'Moschustier', description: 'Das Moschustier hat eine Moschusdrüse zur Parfümherstellung.' },
  'tufted-deer': { name: 'Tufted-Hirsch', description: 'Der Tufted-Hirsch hat eine markante Haarpracht an der Stirn.' },
  'muntjac': { name: 'Muntjak', description: 'Der Muntjak ist ein kleiner Hirsch mit kurzen Hörnern und Stoßzähnen.' },
  'reeves-s-muntjac': { name: 'Reeves Muntjak', description: 'Der Reeves Muntjak ist ein endemischer Hirsch Chinas.' },
  'chinese-water-deer': { name: 'Wasserhirsch', description: 'Der Wasserhirsch hat hervorstehende Stoßzähne und wird auch "Hirsch mit Stoßzähnen" genannt.' },
  'pere-david-s-deer': { name: 'Davidshirsch', description: 'Der Davidshirsch ist eine endemische Art Chinas, die in freier Wildbahn ausgestorben war und wieder eingeführt wurde.' },
  'sika-deer': { name: 'Sika-Hirsch', description: 'Der Sika-Hirsch hat weiße Flecken und kommt in Ostasien vor.' },
  'fallow-deer': { name: 'Damhirsch', description: 'Der Damhirsch hat geweihartige Hörner und stammt aus Europa und Asien.' },
  'red-deer': { name: 'Rotwild', description: 'Das Rotwild ist ein großer Hirsch, Männchen haben mächtige Hörner.' },
  'reindeer': { name: 'Rentier', description: 'Das Rentier ist ein Hirsch der Arktis, beide Geschlechter haben Hörner.' },
  'elk': { name: 'Wapiti', description: 'Das Wapiti ist ein großer Hirsch, Männchen haben mächtige Hörner.' },
  'sambar-deer': { name: 'Sambar-Hirsch', description: 'Der Sambar-Hirsch ist ein großer Hirsch, der in Süd- und Südostasien lebt.' },
  'rusa-deer': { name: 'Rusa-Hirsch', description: 'Der Rusa-Hirsch lebt in Südostasien.' }
};

const missing = getMissing('de');
console.log(`de missing: ${missing.length}`);

// Generate translations
const deNames = {};
for (const animal of missing) {
  const deName = deTranslations[animal.id] || animal.name;
  const deDesc = `${deName} ist ein Tier. ${animal.description}`;
  deNames[animal.id] = { name: deName, description: deDesc };
}

// Write to file
const outputFile = path.join(dataDir, 'de-names.json');
fs.writeFileSync(outputFile, JSON.stringify(deNames, null, 2));
console.log(`Generated ${Object.keys(deNames).length} de translations`);
console.log(`Output: ${outputFile}`);
