const dietTranslations: Record<string, Record<string, string>> = {
  en: { Carnivore: 'Carnivore', Herbivore: 'Herbivore', Omnivore: 'Omnivore', Insectivore: 'Insectivore', Detritivore: 'Detritivore', 'Filter feeder': 'Filter feeder' },
  fr: { Carnivore: 'Carnivore', Herbivore: 'Herbivore', Omnivore: 'Omnivore', Insectivore: 'Insectivore', Detritivore: 'Détritivore', 'Filter feeder': 'Filtreur' },
  es: { Carnivore: 'Carnívoro', Herbivore: 'Herbívoro', Omnivore: 'Omnívoro', Insectivore: 'Insectívoro', Detritivore: 'Detritívoro', 'Filter feeder': 'Filtrador' },
  ja: { Carnivore: '肉食', Herbivore: '草食', Omnivore: '雑食', Insectivore: '虫食', Detritivore: '腐食', 'Filter feeder': '濾過摂食' },
  de: { Carnivore: 'Fleischfresser', Herbivore: 'Pflanzenfresser', Omnivore: 'Allesfresser', Insectivore: 'Insektenfresser', Detritivore: 'Detritivorer', 'Filter feeder': 'Filterfresser' },
  pt: { Carnivore: 'Carnívoro', Herbivore: 'Herbívoro', Omnivore: 'Omnívoro', Insectivore: 'Insetívoro', Detritivore: 'Detritívoro', 'Filter feeder': 'Filtrador' },
  ko: { Carnivore: '육식', Herbivore: '초식', Omnivore: '잡식', Insectivore: '곤충식', Detritivore: '부식', 'Filter feeder': '여과섭식' },
  it: { Carnivore: 'Carnivoro', Herbivore: 'Erbivoro', Omnivore: 'Onnivoro', Insectivore: 'Insettivoro', Detritivore: 'Detritivoro', 'Filter feeder': 'Filtratore' },
  'zh-CN': { Carnivore: '肉食', Herbivore: '草食', Omnivore: '杂食', Insectivore: '食虫', Detritivore: '食碎屑', 'Filter feeder': '滤食' },
  'zh-TW': { Carnivore: '肉食', Herbivore: '草食', Omnivore: '雜食', Insectivore: '食蟲', Detritivore: '食碎屑', 'Filter feeder': '濾食' },
  ar: { Carnivore: 'آكل اللحوم', Herbivore: 'آكل الأعشاب', Omnivore: 'آكلeverything', Insectivore: 'آكل الحشرات', Detritivore: 'آكل التحلل', 'Filter feeder': 'المصفية' },
};

const habitatTranslations: Record<string, Record<string, string>> = {
  en: { Arctic: 'Arctic', Antarctic: 'Antarctic', 'Bamboo Forest': 'Bamboo Forest', Burrows: 'Burrows', Caves: 'Caves', Coast: 'Coast', 'Deciduous Forests': 'Deciduous Forests', Desert: 'Desert', 'Eucalyptus Forest': 'Eucalyptus Forest', Farmland: 'Farmland', Forest: 'Forest', Grassland: 'Grassland', Island: 'Island', Mangrove: 'Mangrove', Mountains: 'Mountains', Ocean: 'Ocean', Rivers: 'Rivers', 'Rocky Areas': 'Rocky Areas', Savanna: 'Savanna', Steppe: 'Steppe', Tundra: 'Tundra', Underground: 'Underground', Urban: 'Urban', Various: 'Various', Wetlands: 'Wetlands' },
  fr: { Arctic: 'Arctique', Antarctic: 'Antarctique', 'Bamboo Forest': 'Forêt de bambous', Burrows: 'Terriers', Caves: 'Grottes', Coast: 'Côte', 'Deciduous Forests': 'Forêts caducifoliées', Desert: 'Désert', 'Eucalyptus Forest': 'Forêt d\'eucalyptus', Farmland: 'Terres agricoles', Forest: 'Forêt', Grassland: 'Prairie', Island: 'Île', Mangrove: 'Mangrove', Mountains: 'Montagnes', Ocean: 'Océan', Rivers: 'Rivières', 'Rocky Areas': 'Zones rocheuses', Savanna: 'Savane', Steppe: 'Steppe', Tundra: 'Toundra', Underground: 'Souterrain', Urban: 'Urbain', Various: 'Divers', Wetlands: 'Zones humides' },
  es: { Arctic: 'Ártico', Antarctic: 'Antártico', 'Bamboo Forest': 'Bosque de bambú', Burrows: 'Madrigueras', Caves: 'Cuevas', Coast: 'Costa', 'Deciduous Forests': 'Bosques caducifolios', Desert: 'Desierto', 'Eucalyptus Forest': 'Bosque de eucalipto', Farmland: 'Tierras agrícolas', Forest: 'Bosque', Grassland: 'Pradera', Island: 'Isla', Mangrove: 'Manglar', Mountains: 'Montañas', Ocean: 'Océano', Rivers: 'Ríos', 'Rocky Areas': 'Áreas rocosas', Savanna: 'Sabana', Steppe: 'Estepa', Tundra: 'Tundra', Underground: 'Subterráneo', Urban: 'Urbano', Various: 'Varios', Wetlands: 'Humedales' },
  ja: { Arctic: '北極', Antarctic: '南極', 'Bamboo Forest': '竹林', Burrows: '巣穴', Caves: '洞窟', Coast: '海岸', 'Deciduous Forests': '落葉樹林', Desert: '砂漠', 'Eucalyptus Forest': 'ユーカリ林', Farmland: '農地', Forest: '森林', Grassland: '草原', Island: '島', Mangrove: 'マングローブ', Mountains: '山地', Ocean: '海洋', Rivers: '河川', 'Rocky Areas': '岩場', Savanna: 'サバナ', Steppe: 'ステップ', Tundra: 'ツンドラ', Underground: '地下', Urban: '都市', Various: ' various', Wetlands: '湿地' },
  de: { Arctic: 'Arktis', Antarctic: 'Antarktis', 'Bamboo Forest': 'Bambuswald', Burrows: 'Erdbaue', Caves: 'Höhlen', Coast: 'Küste', 'Deciduous Forests': 'Laubwälder', Desert: 'Wüste', 'Eucalyptus Forest': 'Eukalyptuswald', Farmland: 'Ackerland', Forest: 'Wald', Grassland: 'Grasland', Island: 'Insel', Mangrove: 'Mangrove', Mountains: 'Berge', Ocean: 'Ozean', Rivers: 'Flüsse', 'Rocky Areas': 'Felsige Gebiete', Savanna: 'Savanne', Steppe: 'Steppe', Tundra: 'Tundra', Underground: 'Unterirdisch', Urban: 'Städtisch', Various: 'Verschiedene', Wetlands: 'Feuchtgebiete' },
  pt: { Arctic: 'Ártico', Antarctic: 'Antártico', 'Bamboo Forest': 'Floresta de bambu', Burrows: 'Tocas', Caves: 'Cavernas', Coast: 'Costa', 'Deciduous Forests': 'Florestas caducifólias', Desert: 'Deserto', 'Eucalyptus Forest': 'Floresta de eucalipto', Farmland: 'Terras agrícolas', Forest: 'Floresta', Grassland: 'Pradaria', Island: 'Ilha', Mangrove: 'Mangue', Mountains: 'Montanhas', Ocean: 'Oceano', Rivers: 'Rios', 'Rocky Areas': 'Áreas rochosas', Savanna: 'Savana', Steppe: 'Estepes', Tundra: 'Tundra', Underground: 'Subterrâneo', Urban: 'Urbano', Various: 'Vários', Wetlands: 'Áreas alagadas' },
  ko: { Arctic: '북극', Antarctic: '남극', 'Bamboo Forest': '대나무 숲', Burrows: '굴', Caves: '동굴', Coast: '해안', 'Deciduous Forests': '낙엽수림', Desert: '사막', 'Eucalyptus Forest': '유칼립투스 숲', Farmland: '농지', Forest: '숲', Grassland: ' 초원', Island: '섬', Mangrove: '맹그로브', Mountains: '산', Ocean: '바다', Rivers: '강', 'Rocky Areas': '바위 지대', Savanna: '사바나', Steppe: '스텝', Tundra: '툰드라', Underground: '지하', Urban: '도시', Various: '다양', Wetlands: '습지' },
  it: { Arctic: 'Artico', Antarctic: 'Antartico', 'Bamboo Forest': 'Foresta di bambù', Burrows: 'Tane', Caves: 'Grotte', Coast: 'Costa', 'Deciduous Forests': 'Foreste caducifoglie', Desert: 'Deserto', 'Eucalyptus Forest': 'Foresta di eucalipto', Farmland: 'Terre agricole', Forest: 'Foresta', Grassland: 'Prateria', Island: 'Isola', Mangrove: 'Mangrovie', Mountains: 'Montagne', Ocean: 'Oceano', Rivers: 'Fiumi', 'Rocky Areas': 'Aree rocciose', Savanna: 'Savana', Steppe: 'Steppa', Tundra: 'Tundra', Underground: 'Sotterraneo', Urban: 'Urbano', Various: 'Vari', Wetlands: 'Zone umide' },
  'zh-CN': { Arctic: '北极', Antarctic: '南极', 'Bamboo Forest': '竹林', Burrows: '洞穴', Caves: '山洞', Coast: '海岸', 'Deciduous Forests': '落叶林', Desert: '沙漠', 'Eucalyptus Forest': '桉树林', Farmland: '农田', Forest: '森林', Grassland: '草原', Island: '岛屿', Mangrove: '红树林', Mountains: '山区', Ocean: '海洋', Rivers: '河流', 'Rocky Areas': '岩石区', Savanna: '热带草原', Steppe: '草原', Tundra: '冻原', Underground: '地下', Urban: '城市', Various: '多种', Wetlands: '湿地' },
  'zh-TW': { Arctic: '北極', Antarctic: '南極', 'Bamboo Forest': '竹林', Burrows: '洞穴', Caves: '山洞', Coast: '海岸', 'Deciduous Forests': '落葉林', Desert: '沙漠', 'Eucalyptus Forest': '桉樹林', Farmland: '農田', Forest: '森林', Grassland: '草原', Island: '島嶼', Mangrove: '紅樹林', Mountains: '山區', Ocean: '海洋', Rivers: '河流', 'Rocky Areas': '岩石區', Savanna: '熱帶草原', Steppe: '草原', Tundra: '凍原', Underground: '地下', Urban: '城市', Various: '多種', Wetlands: '濕地' },
  ar: { Arctic: 'القطب الشمالي', Antarctic: 'القطب الجنوبي', 'Bamboo Forest': 'غابة الخيزران', Burrows: 'جحور', Caves: 'كهوف', Coast: 'ساحل', 'Deciduous Forests': 'غابات الأوراق النفضية', Desert: 'صحراء', 'Eucalyptus Forest': 'غابة الأكاليبتوس', Farmland: 'أراضي زراعية', Forest: 'غابة', Grassland: 'مراعي', Island: 'جزيرة', Mangrove: 'سنديان', Mountains: 'جبال', Ocean: 'محيط', Rivers: 'أنهار', 'Rocky Areas': 'مناطق صخرية', Savanna: 'سافانا', Steppe: 'سهوب', Tundra: 'تندرا', Underground: 'تحت الأرض', Urban: 'حضري', Various: 'متنوع', Wetlands: 'أراضي رطبة' },
};

const regionTranslations: Record<string, Record<string, string>> = {
  en: { Africa: 'Africa', Asia: 'Asia', 'North America': 'North America', 'South America': 'South America', Europe: 'Europe', Oceania: 'Oceania', Australia: 'Australia', Antarctica: 'Antarctica', 'Central America': 'Central America', Caribbean: 'Caribbean', 'Middle East': 'Middle East', Arctic: 'Arctic', Antarctic: 'Antarctic', Global: 'Global', Worldwide: 'Worldwide', Pacific: 'Pacific', Atlantic: 'Atlantic', Indian: 'Indian', Mediterranean: 'Mediterranean' },
  fr: { Africa: 'Afrique', Asia: 'Asie', 'North America': 'Amérique du Nord', 'South America': 'Amérique du Sud', Europe: 'Europe', Oceania: 'Océanie', Australia: 'Australie', Antarctica: 'Antarctique', 'Central America': 'Amérique centrale', Caribbean: 'Caraïbes', 'Middle East': 'Moyen-Orient', Arctic: 'Arctique', Antarctic: 'Antarctique', Global: 'Mondial', Worldwide: 'Monde entier', Pacific: 'Pacifique', Atlantic: 'Atlantique', Indian: 'Indien', Mediterranean: 'Méditerranée' },
  es: { Africa: 'África', Asia: 'Asia', 'North America': 'América del Norte', 'South America': 'América del Sur', Europe: 'Europa', Oceania: 'Oceanía', Australia: 'Australia', Antarctica: 'Antártida', 'Central America': 'América Central', Caribbean: 'Caribe', 'Middle East': 'Oriente Medio', Arctic: 'Ártico', Antarctic: 'Antártico', Global: 'Global', Worldwide: 'Mundial', Pacific: 'Pacífico', Atlantic: 'Atlántico', Indian: 'Índico', Mediterranean: 'Mediterráneo' },
  ja: { Africa: 'アフリカ', Asia: 'アジア', 'North America': '北アメリカ', 'South America': '南アメリカ', Europe: 'ヨーロッパ', Oceania: 'オセアニア', Australia: 'オーストラリア', Antarctica: '南極', 'Central America': '中央アメリカ', Caribbean: 'カリブ海', 'Middle East': '中東', Arctic: '北極', Antarctic: '南極', Global: '全世界', Worldwide: '全世界', Pacific: '太平洋', Atlantic: '大西洋', Indian: 'インド洋', Mediterranean: '地中海' },
  de: { Africa: 'Afrika', Asia: 'Asien', 'North America': 'Nordamerika', 'South America': 'Südamerika', Europe: 'Europa', Oceania: 'Ozeanien', Australia: 'Australien', Antarctica: 'Antarktis', 'Central America': 'Zentralamerika', Caribbean: 'Karibik', 'Middle East': 'Naher Osten', Arctic: 'Arktis', Antarctic: 'Antarktis', Global: 'Global', Worldwide: 'Weltweit', Pacific: 'Pazifik', Atlantic: 'Atlantik', Indian: 'Indischer Ozean', Mediterranean: 'Mittelmeer' },
  pt: { Africa: 'África', Asia: 'Ásia', 'North America': 'América do Norte', 'South America': 'América do Sul', Europe: 'Europa', Oceania: 'Oceania', Australia: 'Austrália', Antarctica: 'Antártida', 'Central America': 'América Central', Caribbean: 'Caribe', 'Middle East': 'Oriente Médio', Arctic: 'Ártico', Antarctic: 'Antártico', Global: 'Global', Worldwide: 'Mundial', Pacific: 'Pacífico', Atlantic: 'Atlântico', Indian: 'Índico', Mediterranean: 'Mediterrâneo' },
  ko: { Africa: '아프리카', Asia: '아시아', 'North America': '북미', 'South America': '남미', Europe: '유럽', Oceania: '오세아니아', Australia: '호주', Antarctica: '남극', 'Central America': '중앙아메리카', Caribbean: '카리브', 'Middle East': '중동', Arctic: '북극', Antarctic: '남극', Global: '전 세계', Worldwide: '전 세계', Pacific: '태평양', Atlantic: '대서양', Indian: '인도양', Mediterranean: '지중해' },
  it: { Africa: 'Africa', Asia: 'Asia', 'North America': 'Nord America', 'South America': 'Sud America', Europe: 'Europa', Oceania: 'Oceania', Australia: 'Australia', Antarctica: 'Antartide', 'Central America': 'America Centrale', Caribbean: 'Caraibi', 'Middle East': 'Medio Oriente', Arctic: 'Artico', Antarctic: 'Antartico', Global: 'Globale', Worldwide: 'Mondiale', Pacific: 'Pacifico', Atlantic: 'Atlantico', Indian: 'Indiano', Mediterranean: 'Mediterraneo' },
  'zh-CN': { Africa: '非洲', Asia: '亚洲', 'North America': '北美洲', 'South America': '南美洲', Europe: '欧洲', Oceania: '大洋洲', Australia: '澳大利亚', Antarctica: '南极洲', 'Central America': '中美洲', Caribbean: '加勒比', 'Middle East': '中东', Arctic: '北极', Antarctic: '南极', Global: '全球', Worldwide: '全世界', Pacific: '太平洋', Atlantic: '大西洋', Indian: '印度洋', Mediterranean: '地中海' },
  'zh-TW': { Africa: '非洲', Asia: '亞洲', 'North America': '北美洲', 'South America': '南美洲', Europe: '歐洲', Oceania: '大洋洲', Australia: '澳大利亞', Antarctica: '南極洲', 'Central America': '中美洲', Caribbean: '加勒比', 'Middle East': '中東', Arctic: '北極', Antarctic: '南極', Global: '全球', Worldwide: '全世界', Pacific: '太平洋', Atlantic: '大西洋', Indian: '印度洋', Mediterranean: '地中海' },
  ar: { Africa: 'أفريقيا', Asia: 'آسيا', 'North America': 'أمريكا الشمالية', 'South America': 'أمريكا الجنوبية', Europe: 'أوروبا', Oceania: 'أوقيانوسيا', Australia: 'أستراليا', Antarctica: 'القارة القطبية الجنوبية', 'Central America': 'أمريكا الوسطى', Caribbean: 'الكاريبي', 'Middle East': 'الشرق الأوسط', Arctic: 'القطب الشمالي', Antarctic: 'القطب الجنوبي', Global: 'عالمي', Worldwide: 'في جميع أنحاء العالم', Pacific: 'المحيط الهادئ', Atlantic: 'الأطلسي', Indian: 'المحيط الهندي', Mediterranean: 'البحر الأبيض المتوسط' },
};

export function translateValue(value: string, field: 'habitat' | 'diet' | 'region', locale: string): string {
  if (locale === 'en' || !value) return value;

  let map: Record<string, string>;
  if (field === 'diet') map = dietTranslations[locale] || dietTranslations.en;
  else if (field === 'habitat') map = habitatTranslations[locale] || habitatTranslations.en;
  else map = regionTranslations[locale] || regionTranslations.en;

  return map[value] || value;
}
